"use strict";

/*
 * Client for the legacy KeePassHTTP protocol as served by the MiixKey Pro
 * (the protocol of the original KeePassHttp plugin for KeePass 2.x,
 * https://github.com/pfn/keepasshttp).
 *
 * Transport is JSON over plain HTTP. Confidentiality of credential fields
 * relies on AES-256-CBC with a 256-bit key that is generated by this client
 * during association and stored on the device. Every message carries a fresh
 * 16-byte nonce (also the CBC IV) and a verifier: the base64 string of the
 * nonce, encrypted with the shared key. Both sides prove key possession by
 * checking the other side's verifier.
 */

const KeePassHttp = (() => {
	const DEFAULT_HOST = "172.16.8.1";
	const DEFAULT_PORT = 19455;

	const textEncoder = new TextEncoder();
	const textDecoder = new TextDecoder();

	function bytesToBase64(bytes) {
		let binary = "";
		for (const byte of bytes) {
			binary += String.fromCharCode(byte);
		}
		return btoa(binary);
	}

	function base64ToBytes(base64) {
		const binary = atob(base64);
		const bytes = new Uint8Array(binary.length);
		for (let i = 0; i < binary.length; i++) {
			bytes[i] = binary.charCodeAt(i);
		}
		return bytes;
	}

	function importKey(keyBytes) {
		return crypto.subtle.importKey("raw", keyBytes, { name: "AES-CBC" }, false, ["encrypt", "decrypt"]);
	}

	async function encryptField(cryptoKey, iv, plainText) {
		const cipher = await crypto.subtle.encrypt({ name: "AES-CBC", iv }, cryptoKey, textEncoder.encode(plainText));
		return bytesToBase64(new Uint8Array(cipher));
	}

	async function decryptField(cryptoKey, iv, cipherBase64) {
		const plain = await crypto.subtle.decrypt({ name: "AES-CBC", iv }, cryptoKey, base64ToBytes(cipherBase64));
		return textDecoder.decode(plain);
	}

	async function getConfig() {
		const stored = await browser.storage.local.get(["host", "port", "associationId", "associationKey"]);
		return {
			host: stored.host || DEFAULT_HOST,
			port: stored.port || DEFAULT_PORT,
			associationId: stored.associationId || null,
			associationKey: stored.associationKey || null
		};
	}

	function endpoint(config) {
		return `http://${config.host}:${config.port}/`;
	}

	async function send(config, request) {
		let response;
		try {
			response = await fetch(endpoint(config), {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify(request)
			});
		} catch (error) {
			throw new Error(`Could not reach MiixKey at ${endpoint(config)}. Make sure the device is connected and unlocked. (${error.message})`);
		}
		if (!response.ok) {
			throw new Error(`MiixKey answered with HTTP ${response.status}.`);
		}
		return response.json();
	}

	// The MiixKey reports its own failure reason in a response `Error` string
	// (not part of the reference protocol); append it when present.
	function deviceError(baseMessage, response) {
		const detail = response && typeof response.Error === "string" && response.Error.trim();
		return new Error(detail ? `${baseMessage} (device: ${detail})` : baseMessage);
	}

	async function makeNonceAndVerifier(cryptoKey) {
		const iv = crypto.getRandomValues(new Uint8Array(16));
		const nonce = bytesToBase64(iv);
		const verifier = await encryptField(cryptoKey, iv, nonce);
		return { iv, nonce, verifier };
	}

	async function verifyResponse(response, cryptoKey) {
		if (!response.Nonce || !response.Verifier) {
			throw new Error("MiixKey response is missing its verifier.");
		}
		const iv = base64ToBytes(response.Nonce);
		let plain;
		try {
			plain = await decryptField(cryptoKey, iv, response.Verifier);
		} catch {
			throw new Error("Could not verify the MiixKey response. The stored key may be stale; connect again.");
		}
		if (plain !== response.Nonce) {
			throw new Error("MiixKey response failed verification.");
		}
		return iv;
	}

	async function requireAssociation() {
		const config = await getConfig();
		if (!config.associationId || !config.associationKey) {
			throw new Error("Not connected to MiixKey yet. Open the MiixKey popup and press Connect first.");
		}
		const cryptoKey = await importKey(base64ToBytes(config.associationKey));
		return { config, cryptoKey };
	}

	async function newRequest(requestType) {
		const { config, cryptoKey } = await requireAssociation();
		const { iv, nonce, verifier } = await makeNonceAndVerifier(cryptoKey);
		const request = {
			RequestType: requestType,
			TriggerUnlock: false,
			Id: config.associationId,
			Nonce: nonce,
			Verifier: verifier
		};
		return { config, cryptoKey, iv, request };
	}

	async function associate() {
		const config = await getConfig();
		const keyBytes = crypto.getRandomValues(new Uint8Array(32));
		const keyBase64 = bytesToBase64(keyBytes);
		const cryptoKey = await importKey(keyBytes);
		const { nonce, verifier } = await makeNonceAndVerifier(cryptoKey);
		const response = await send(config, {
			RequestType: "associate",
			Key: keyBase64,
			Nonce: nonce,
			Verifier: verifier
		});
		if (!response.Success || !response.Id) {
			throw deviceError("MiixKey refused the association. Confirm the request on the device and try again.", response);
		}
		await verifyResponse(response, cryptoKey);
		await browser.storage.local.set({
			associationId: response.Id,
			associationKey: keyBase64
		});
		return response.Id;
	}

	async function testAssociate() {
		const { config, cryptoKey, request } = await newRequest("test-associate");
		const response = await send(config, request);
		if (!response.Success) {
			return false;
		}
		// The MiixKey firmware (1.8.4.2) omits Nonce/Verifier on successful
		// test-associate replies, unlike the reference implementation and
		// unlike its own get-logins replies. Nothing sensitive rides on this
		// response, so verify it only when the fields are present.
		if (response.Nonce || response.Verifier) {
			await verifyResponse(response, cryptoKey);
		}
		return true;
	}

	async function decryptEntry(entry, cryptoKey, iv) {
		return {
			name: entry.Name ? await decryptField(cryptoKey, iv, entry.Name) : "",
			login: entry.Login ? await decryptField(cryptoKey, iv, entry.Login) : "",
			password: entry.Password ? await decryptField(cryptoKey, iv, entry.Password) : "",
			uuid: entry.Uuid ? await decryptField(cryptoKey, iv, entry.Uuid) : ""
		};
	}

	async function getLogins(url, submitUrl) {
		const { config, cryptoKey, iv, request } = await newRequest("get-logins");
		request.Url = await encryptField(cryptoKey, iv, url);
		request.SubmitUrl = await encryptField(cryptoKey, iv, submitUrl || url);
		const response = await send(config, request);
		if (!response.Success) {
			throw deviceError("MiixKey rejected the request. Approve it on the device, or connect again.", response);
		}
		const responseIv = await verifyResponse(response, cryptoKey);
		const entries = [];
		for (const entry of response.Entries || []) {
			entries.push(await decryptEntry(entry, cryptoKey, responseIv));
		}
		return entries;
	}

	function forgetAssociation() {
		return browser.storage.local.remove(["associationId", "associationKey"]);
	}

	return {
		DEFAULT_HOST,
		DEFAULT_PORT,
		getConfig,
		associate,
		testAssociate,
		getLogins,
		forgetAssociation
	};
})();
